ToDo.Web/Controllers/StatusController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDo.Data;
using ToDo.Models;
using ToDo.Repository.Shared.Abstract;

namespace ToDo.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StatusController : Controller
    {
       private readonly IRepository<Status> _statusRepository;

        public StatusController(IRepository<Status> statusRepository)
        {
            _statusRepository = statusRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Index2()
        //{
        //    return View(_context.Statuses.ToList());
        //}
        [AllowAnonymous]
        public IActionResult GetAllStatus()
        {
           
            return Json(new { data = _statusRepository.GetAll() });
        }

        [HttpPost]
        public IActionResult DeleteStatus(int id)
        {
            _statusRepository.Delete(id);
            return Ok("İşlem Başarılı");
        }


        //public IActionResult DeleteStatus2(int id)
        //{
        //    var item = _context.Statuses.Find(id);
        //    _context.Statuses.Remove(item);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index2");
        //}

        //public IActionResult Add()
        //{
        //    return View();
        //}

        [HttpPost]
        public IActionResult Add(Status status)
        {
            
            return Ok(_statusRepository.Add(status));
        }

        //[HttpPost]
        //public IActionResult Add2(Status status)
        //{
        //    _context.Statuses.Add(status);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index2");
        //}

        [HttpPost]
        public IActionResult Update(Status status)
        {
            _statusRepository.Update(status);
            return Ok(status);

        }



        //public IActionResult Update2(int id)
        //{
        //    return View(_context.Statuses.Find(id));
        //}
        //[HttpPost]
        //public IActionResult Update2(Status status)
        //{

        //    if (status != null && ModelState.IsValid)
        //    {
        //        _context.Statuses.Update(status);
        //        _context.SaveChanges();
        //    }
        //    return RedirectToAction("Index2");

        //}
    }
}

ToDo.Web/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDo.Data;
using ToDo.Models;
using ToDo.Repository.Shared.Abstract;

namespace ToDo.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagController : Controller
    {
        private readonly IRepository<Tag> _tagRepository;

        public TagController(IRepository<Tag> tagRepository)
        {
            _tagRepository = tagRepository;
        }

        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult GetAllTags()
        {
            return Json(new { data = _tagRepository.GetAll() });
        }

        [HttpPost]
        public IActionResult DeleteTag(int id)
        {
            _tagRepository.Delete(id);
            
            return Ok("İşlem Başarılı");
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
          
            return Ok(_tagRepository.Add(tag));

        }

        [HttpPost]
        public IActionResult Update(Tag tag)
        {
            _tagRepository.Update(tag);
            return Ok(tag);

        }
    }
}

ToDo.Web/Controllers/TodoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using ToDo.Data;
using ToDo.Models;
using ToDo.Repository.Abstract;


namespace ToDo.Web.Controllers
{
    [Authorize(Roles = "User")]
    public class TodoController : Controller
    {
       private readonly ITodoRepository _todoRepository;

        public TodoController(ITodoRepository repository)
        {
            _todoRepository = repository;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult GetAll()
        {

            
            return Json(new
            {
                data = _todoRepository.GetAll(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)))
            });
        }

        public IActionResult RemoveTag(int todoId, int tagId)
        {
            _todoRepository.RemoveTag(todoId, tagId);
            return Ok("işlem başarılı");

        }

        public IActionResult Add(Todo todo, int[] tags)
        {
            _todoRepository.Add(todo, int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), tags);
            return Ok();
        }

        //bu metodu http post ile de yapılabilir. Ancak çeşit olması açısından bunu get ile çalıştırıyoruz bu seferlik.
        public IActionResult GetById(int id)
        {

            return Json(_todoRepository.GetById(id));

        }
        public IActionResult Update(Todo todo, int[] tags)
        {
            Todo asil = _context.Todos.Include(t => t.Tags).FirstOrDefault(t => t.Id == todo.Id);
            asil.Tags = _context.Tags.Where(t => tags.Contains(t.Id)).ToList();
            asil.Name = todo.Name;
            asil.Description = todo.Description;
            asil.StatusId = todo.StatusId;


            _context.Todos.Update(asil);
            _context.SaveChanges();
            return Ok();

            //json base65string
            //javascript tarafından arka yuze FormData
        }

        [HttpPost]
        public IActionResult Complete(int todoId)
        {
            Todo todo = _context.Todos.Find(todoId);

            todo.Status = _context.Statuses.FirstOrDefault(s => s.Name == "Tamamlandı");

            _context.Todos.Update(todo);
            _context.SaveChanges();
            return Ok();


        }
    }
}

ToDo.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastr@2.1.4/build/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                         @if(User.IsInRole("Admin"))
                         {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Tag" asp-action="Index">Etiketler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Status" asp-action="Index">Statusler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                            </li>

                        }
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Todo" asp-action="Index">Todo</a>
                            </li>
                        }
                    </ul>
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                          
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="User" asp-action="Profile">
                                        Hoşgeldin ,@User.FindFirst(ClaimTypes.Name).Value
                                    </a>
                                </li>
                            
                           
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Logout">Çıkış Yap</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ToDo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="//cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/toastr@2.1.4/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>